# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mufc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mufc',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mufc',
            name='club',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
